server:
  port: 8092

spring:
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    pool:
      initial-size: 10
      max-size: 10
      max-idle-time: 30m
    properties:
      schema: public

app:
  access-token-store:
    type: BASIC
  jwt:
    private-key: |-
      -----BEGIN EC PRIVATE KEY-----
      MIHcAgEBBEIBkjnY1j0nhAumHi80y2KLZuMJ+iZo6fBcpMJVpKWzsgGszmIoDkkl
      YXMruEZK4/JM3UXNxfSbHFkOKBX1GFKtK5WgBwYFK4EEACOhgYkDgYYABAD5Kfmz
      GL/D83TkffR09bC+/Vr486A90e+kVy/0eC8sjhQxlGAB+B+3RhdWmTiNUwmxHIJ9
      +smhFZOolRUm0LPVdAE2w+eAzjwlRr6COX3m82DhL3Ic9qeG4wA2GZosOJhbBYVD
      a5NTPdyHp9mJyDJ0Ssas8HAAQnc6K20dS4HqUJbTgg==
      -----END EC PRIVATE KEY-----

    public-key: |-
      -----BEGIN PUBLIC KEY-----
      MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQA+Sn5sxi/w/N05H30dPWwvv1a+POg
      PdHvpFcv9HgvLI4UMZRgAfgft0YXVpk4jVMJsRyCffrJoRWTqJUVJtCz1XQBNsPn
      gM48JUa+gjl95vNg4S9yHPanhuMANhmaLDiYWwWFQ2uTUz3ch6fZicgydErGrPBw
      AEJ3OittHUuB6lCW04I=
      -----END PUBLIC KEY-----